apiVersion: apps/v1
kind: Deployment
metadata:
  name: antaeus
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        image: ghcr.io/bpesics/pe:latest
        imagePullPolicy: Always
        ports:
        - name: backend-http
          containerPort: 8000
        envFrom:
        - configMapRef:
            name: antaeus-config-env

        startupProbe:
          httpGet:
            path: /rest/v1/invoices
            port: backend-http
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /rest/health
            port: backend-http
        livenessProbe:
          httpGet:
            path: /rest/health
            port: backend-http