apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-antaeus

commonLabels:
  app: antaeus

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: antaeus-config-env
    envs:
      - _antaeus-config-env